namespace CodeChops.MagicEnums.Attributes;

/// <summary>
/// Add this attribute to the enum record to make the enum members auto-discoverable. 
/// Invoking [Enum].[Member].CreateMember(...) will automatically add an enum member and consume it.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public sealed class DiscoverableEnumMembersAttribute : Attribute
{
	public bool ImplicitDiscoverability { get; }

	/// <param name="implicitDiscoverability">If true, the enum will be generated by referencing a new member: [Enum].[NewMember]. Disabled by default./// </param>
	public DiscoverableEnumMembersAttribute(bool implicitDiscoverability = false)
	{
		this.ImplicitDiscoverability = implicitDiscoverability;
	}
}